language: csharp
mono: none
dotnet: 2.1.301
script:
    - dotnet pack Sms.Abstractions/Sms.Abstractions.csproj -c Release /p:Version=1.0.$TRAVIS_BUILD_NUMBER -o ../output/nupkg/
    - dotnet pack Sms.IletiMerkezi/Sms.IletiMerkezi.csproj -c Release /p:Version=1.0.$TRAVIS_BUILD_NUMBER -o ../output/nupkg/
    - dotnet pack Sms.PostaGuvercini/Sms.PostaGuvercini.csproj -c Release /p:Version=1.0.$TRAVIS_BUILD_NUMBER -o ../output/nupkg/
    - ls ../output/nupkgs/
    - for fn in `find ../output/nupkgs/ -name "*.nupkg"`; do  dotnet nuget push $fn -k $NUGET_KEY -s https://api.nuget.org/v3/index.json  done
